<?php
$this->headTitle('Edit');
$this->headTitle($this->model->getName());
$this->title = $this->model->getName();
?>

<form action="<?php echo $this->url(array('action' => 'edit')); ?>" method="post">
    <input type="checkbox" name="active" value="1" id="active" <?php echo $this->model->isActive() ? ' checked="checked"' : ''; ?> />
    <label for="active">Active

    <?php if ($this->model->names): ?>
        <h4>Display Names</h4>
        <?php foreach ($this->model->names as $alias): ?>
        <div>
            <input type="radio" name="modelName" value="<?php echo $alias->ID; ?>" id="modelName_<?php echo $alias->ID; ?>" <?php echo $this->model->getName() == $alias->name ? ' checked="checked"' : ''; ?>>
            <label for="modelName_<?php echo $alias->ID; ?>"><?php echo $alias->name; ?></label>
        </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php // New Alias ?>

    <h4>Photosets Updated</h4>
    <div><?php echo $this->model->photosetsChecked;?></div>

    <?php // Last Google search date ?>

    <?php // WebLink Stats for this model ?>

    <h4>WebUrls</h4>
    <div><a href="<?php echo $this->url(array('controller' => 'web-url', 'action' => 'index', 'modelid' => $this->model->ID));?>">See WebUrls</a></div>

    <p><input type="submit" value="Update" /></p>

</form>
