<?php
$this->headTitle('Edit');
$this->headTitle($this->model->getName());
$this->title = '<a href="' . $this->url(array('controller' => 'model', 'action' => 'view', 'id' => $this->model->ID), null, true) . '">' . $this->model->getName(). '</a>';
$this->subtitle = 'Edit';
?>

<?php echo $this->partial('model/partials/navigation.phtml', array('model' => $this->model, 'active' => 'edit')); ?>

<form action="<?php echo $this->url(array('action' => 'edit')); ?>" method="post">
    <input type="checkbox" name="active" value="1" id="active" <?php echo $this->model->isActive() ? ' checked="checked"' : ''; ?> />
    <label for="active">Active</label>

    <?php if ($this->model->names): ?>
        <h4>Display Names</h4>
        <?php foreach ($this->model->names as $alias): ?>
        <div class="radio">
            <label>
                <input type="radio" name="modelName" value="<?php echo $alias->ID; ?>" id="modelName_<?php echo $alias->ID; ?>" <?php echo $this->model->getName() == $alias->name ? ' checked="checked"' : ''; ?>>
                <?php echo $alias->name; ?>
            </label>
        </div>
        <?php endforeach; ?>
        <a href="<?php echo $this->url(array('controller' => 'model', 'action' => 'add-alias', 'id' => $this->model->ID)); ?>" class="btn btn-primary">Add Alias</a>
    <?php endif; ?>

    <h4>Photosets Updated</h4>
    <div><?php echo $this->model->photosetsChecked;?></div>

    <h4>WebCrawler Updated</h4>
    <div><?php echo $this->model->webcrawler_updated; ?></div>

    <p><input type="submit" name="submit" value="Update" /></p>

</form>
