<?php
$this->headTitle('Edit');
$this->headTitle($this->model->getName());
$this->title = '<a href="' . $this->url(array('controller' => 'model', 'action' => 'view', 'id' => $this->model->ID), null, true) . '">' . $this->model->getName(). '</a>';
?>

<ul class="nav nav-pills">
    <li>
        <a href="<?php echo $this->url(array('controller'=>'model', 'action'=>'view', 'id' => $this->model->ID), null, true);?>">Gallery</a>
    </li>
    <li class="active">
        <a href="<?php echo $this->url(array('controller'=>'model', 'action'=>'edit', 'id' => $this->photosets[0]->model->ID), null, true);?>">Edit</a>
    </li>
</ul>

<form action="<?php echo $this->url(array('action' => 'edit')); ?>" method="post">
    <input type="checkbox" name="active" value="1" id="active" <?php echo $this->model->isActive() ? ' checked="checked"' : ''; ?> />
    <label for="active">Active</label>

    <?php if ($this->model->names): ?>
        <h4>Display Names</h4>
        <?php foreach ($this->model->names as $alias): ?>
        <div>
            <input type="radio" name="modelName" value="<?php echo $alias->ID; ?>" id="modelName_<?php echo $alias->ID; ?>" <?php echo $this->model->getName() == $alias->name ? ' checked="checked"' : ''; ?>>
            <label for="modelName_<?php echo $alias->ID; ?>"><?php echo $alias->name; ?></label>
        </div>
        <?php endforeach; ?>
        <form method="post">
            <input type="text" name="alias">
            <input type="submit" name="submit" value="Add Name" />
        </form>
    <?php endif; ?>

    <?php // New Alias ?>

    <h4>Photosets Updated</h4>
    <div><?php echo $this->model->photosetsChecked;?></div>

    <?php // Last Google search date ?>

    <?php // WebLink Stats for this model ?>

    <h4>WebUrls</h4>
    <div><a href="<?php echo $this->url(array('controller' => 'web-url', 'action' => 'index', 'modelid' => $this->model->ID));?>">See WebUrls</a></div>

    <p><input type="submit" name="submit" value="Update" /></p>

</form>
