<?php
    $this->titleonly = 'Ranking';
    $this->headTitle($this->titleonly);
?>
<div class="row">
    <div class="col-md-8 col-sm-10 col-xs-12 col-md-offset-2 col-sm-offset-1">
	<div class="row">
            <?php
                foreach ($this->modelKeys as $modelKey):
                    $model = $this->models[$modelKey];
                    $photoset = $model->getRandomPhotoset();
            ?>
            <div class="col-xs-6">
                <div class="thumbnail">
                    <div class="image medium">
                        <a href="<?php echo $this->url(array('controller'=>'gallery', 'action'=>'view', 'id'=>$model->ID, 'photoset' => $photoset->id)); ?>">
                            <img src="<?php echo $this->url(array('controller'=>'image', 'action'=>'medium', 'id'=>rawurlencode($photoset->thumbnail), 'page' => null)); ?>" />
                        </a>
                        <div class="name">
                            <a href="<?php echo $this->url(array('action' => 'view', 'id' => $model->ID)); ?>"><?php echo $model->getName(); ?></a>
                        </div>
                    </div>
                    <div class="caption">
                        <strong class="block">
                            
                        </strong>

                        <div class="pull-right">
                             <a href="<?php echo $this->url(array('controller' => 'gallery', 'action' => 'thumbnail', 'id' => $model->ID, 'photoset' => $photoset->id)); ?>" class="<?php echo $photoset->manual_thumbnail ? 'text-success' : 'text-danger'; ?>"><i class="<?php echo $photoset->manual_thumbnail ? 'fa fa-flag' : 'fa fa-flag-o'; ?>"></i></a>
                        </div>
                        <div class="pull-left">
                            <i class="fa fa-thumbs-o-up"></i> <?php echo $model->ranking; ?> <span class="badge"><i class="fa fa-star"></i> <?php echo count($this->models->toArray()); ?></span>&nbsp;
                        </div>
                        <div class=""pull-left">
                            <i class="fa fa-picture-o"></i> <?php echo count($model->photosets); ?>&nbsp;
                        </div>
                        <form action="<?php echo $this->url(array('action' => 'ranking')); ?>" method="post">
                            <div class="checkbox">
                                <label>
                                <input type="checkbox" id="search<?php echo $model->ID; ?>" name="search"<?php echo $model->search ? ' checked="checked"' : ''; ?> />
                                <i class="fa fa-search"></i> <?php echo $this->date($model->datesearched); ?>
                                </label>
                                
                            </div>
                            <!-- Stats
                            <a href="weblinks.php?action=0&model={$link.id}">WL = {$link.weblinks}</a>
                            <a href="weblinks.php?action=2&model={$link.id}">WT = {$link.webthumbs}</a>
                            <a href="weblinks.php?action=6&model={$link.id}">WI = {$link.webimages}</a>
                             -->
                            <input type="hidden" name="model_id" value="<?php echo $model->ID; ?>" />
                            <input type="hidden" name="model_ranking" value="<?php echo $model->ranking; ?>" />
                            <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-thumbs-o-up"></i> God Like!</button>
                        </form>

                        <?php //var_dump($model->getWebLinkStats()->toArray() ); ?>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
	</div>
    </div>
</div>

<ul id="menu" class="clearfix">
    <li><a href="<?php echo $this->url(array('action' => 'ranking'));?>">Try Again</a></li>
</ul>
