<?php $this->title = 'Thumbnailer'; ?>

<?php if ($this->photosets): ?>

<div class="row">

<?php
if (count($this->photosets)):
foreach ($this->photosets as $photoset):
?>

<div class="col-xs-4 col-sm-3 col-md-2">
    <a href="<?php echo $this->url(array('controller' => 'gallery', 'action' => 'thumbnail', 'photoset' => $photoset->id)) ?>" class="thumbnail">
        <div class="image thumb">
        
            <img data-src="holder.js/100%x168" src="<?php echo $this->url(array('controller'=>'image', 'action'=>'thumbnail', 'id'=>rawurlencode($photoset->thumbnail), 'page' => null)); ?>" />
            
            <div class="name">
                <?php echo $photoset->model->getName(); ?><br />
                <i class="fa fa-thumbs-o-up"></i> <?php echo $this->escape($photoset->model->ranking)?>
            </div>
        </div>
    </a>
</div>

<?php
endforeach;
else:?>
    <div class="col-md-12">
        <p>No photosets need thumbnails to be set</p>
    </div>
<?php endif; ?>

</div>

<?php endif; ?>

<?php echo $this->partial('pagination.phtml', array('paginator' => $this->paginator))?>