<div class="row">
    <div class="col-md-4 col-sm-6 col-xs-10 col-md-offset-4 col-sm-offset-3 col-xs-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2>Forgotten Password <i class="fa fa-sign-in"></i></h2>
            </div>
            <div class="panel-body">
                <?php 
                if ($this->form):
                    echo $this->form;
                else:
                ?>
                <p>Cannot reset your password using the email and key method.</p>
                <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'forgotten'), null, true) ?>" class="btn btn-default">Try again</a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
