<?php
$load = sys_getloadavg();
?>
<div class="row">
    <div class="pull-left">
        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <?php echo $load[0].','.$load[1].','.$load[2]; ?>
        <?php endif; ?>
    </div>
    <div class="pull-right">
        <span class="mode">
        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <?php echo $this->mode; ?>
        <?php endif; ?>
        </span>
        <span class="version">
            v2.2.1
        </span>
    </div>
</div>