<?php
$load = sys_getloadavg();
$temp = str_replace('+', '', trim(str_ireplace('Core0 Temp:', '', exec('sensors | sed -n 3p'))));

?>
<div class="row">
    <div class="pull-left">
        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
        <div class="cpu">
            <?php echo implode(', ', $load) . ', ' . $temp; ?>
        </div>
        <?php endif; ?>
    </div>
    <div class="pull-right">
        <span class="mode">
        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <?php echo $this->mode; ?>
        <?php endif; ?>
        </span>
        <span class="version">
            v2.2.2
        </span>
    </div>
</div>