<?php
$load = sys_getloadavg();
$temp = str_replace('+', '', trim(str_ireplace('Core0 Temp:', '', exec('sensors | sed -n 3p'))));

?>
<div class="row">
    <div class="pull-left">
        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
        <div class="cpu">
            <?php echo implode(', ', $load) . ', ' . $temp; ?>
        </div>
        <?php endif; ?>
    </div>
    <div class="pull-right">
        <span class="mode">
        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <?php echo $this->mode; ?>
        <?php endif; ?>
        </span>
        <span class="version">
            v2.2.3
        </span>
    </div>
</div>
<div class="row">
    <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
    <?php
        $memcache_obj = new Memcache;
        $memcache_obj->addServer('localhost', 11211);
        $stats = $memcache_obj->getStats();
    ?>
    Memcache - Items <?php echo $stats['curr_items']; ?>;
    Evictions <?php echo $stats['evictions']; ?>;
    Reclaimed <?php echo $stats['reclaimed']; ?>
    <?php
        // _d($stats['evictions'], $stats['total_items'], $stats['curr_items'], $stats);
    ?>
    <?php endif; ?>
</div>
