<!-- Static navbar -->
<div class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        <a class="navbar-brand" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'),null ,true); ?>"><i class="fa fa-leaf"></i> Goddesses</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                <li><a href="<?php echo $this->url(array('controller' => 'model', 'action' => 'add', 'page' => null, 'search' => null, 'order' => null), null, true);?>">Add new model</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'model', 'action' => 'ranking'), null, true); ?>">Ranking</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'model', 'action' => 'stats'), null, true); ?>">Stats</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'web-resource', 'action' => 'index'), null, true); ?>">Web Resources</a></li>
                <?php endif; ?>
            </ul>
            
            <!-- Right Links -->
            <ul class="nav navbar-nav navbar-right">
                <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                <li><a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout'),null ,true); ?>">Log out</a></li>
                <?php else: ?>
                <li><a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'login'),null ,true); ?>">Log in</a></li>
                <?php endif;?>
            </ul>
            
            <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <!-- Search -->
            <div class="col-xs-12 col-sm-4 col-md-4">
                <form class="navbar-form" role="search" method="get" id="search-form" name="search-form">
                    <div class="input-group">
                        <input type="text" class="form-control input-sm" placeholder="Search" id="query" name="query" value="">
                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-primary btn-sm"><span class="fa fa-search"></span></button>
                        </div>
                    </div>
                </form>
            </div>
            <?php endif; ?>
            
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</div>

