<div class="col-xs-4 col-sm-3 col-md-2">
    <a href="<?php echo $this->url(array('controller'=>'image', 'action'=>'large', 'id'=>rawurlencode($this->uri)), null, true); ?>" class="thumbnail">
        <div class="image">
            <img src="<?php echo $this->url(array('controller'=>'image', 'action'=>'thumbnail', 'id'=>rawurlencode($this->uri)), null, true); ?>" />
        </div>
    </a>
</div>