<?php if ($this->webResources): ?>
<table>
    <thead>
        <tr>
            <th>Website</th>
            <th>Frequency</th>
            <th>Next Check</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->webResources as $webResource): ?>
        <tr>
            <td><a href="<?php echo $this->url(array('action' => 'test', 'id' => $webResource->id)); ?>"><?php echo $webResource->website; ?></a></td>
            <td><?php echo $webResource->frequency; ?></td>
            <td><?php echo $webResource->nextCheck; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif;?>