<div class="row">
    <div class="col-md-12">
        <form action="" method="get" class="form-horizontal">
            <div class="input-group col-md-12">
                <input type="text" name="url" class="form-control input-md" value="<?php echo $this->url ?>">



                <div class="input-group-btn">

                    <div class="btn-group" data-toggle="buttons">
                    <label class="btn btn-md btn-primary">
                        <input type="checkbox" name="filter" autocomplete="off">Filter
                    </label>
                    </div>

                    <button type="submit" class="btn btn-primary btn-md">Go</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class=""row">
    <div class="col-md-12">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#links" aria-controls="links" role="tab" data-toggle="tab">Links</a></li>
            <li role="presentation"><a href="#images" aria-controls="images" role="tab" data-toggle="tab">Images</a></li>
            <li role="presentation"><a href="#source" aria-controls="source" role="tab" data-toggle="tab">Source</a></li>
            <li role="presentation"><a href="#curl" aria-controls="curl" role="tab" data-toggle="tab">Curl</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">

            <div role="tabpanel" class="tab-pane active" id="links">
                <?php if ($this->links): ?>
                    <h1>Showing Links</h1>
                    <?php foreach($this->links as $link): ?>
                        <div class="col-md-12">
                            <a href="<?php echo $this->url(array('controller' => 'browser', 'action' => 'index')) .'?' . http_build_query(array('url' => $link)); ?>">
                                <?php echo $link; ?>
                            </a>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>

            <div role="tabpanel" class="tab-pane" id="images">
                <?php if ($this->images): ?>
                    <h1>Showing Images</h1>
                    <?php foreach($this->images as $image): ?>
                        <div class="col-md-12">
                            <a href="<?php echo $this->url(array('controller' => 'browser', 'action' => 'index')) .'?' . http_build_query(array('url' => $image)); ?>">
                                <?php echo $image; ?>
                            </a>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php if ($this->contentType == 'image/jpeg'): ?>
                    <h1>Showing image</h1>
                    <img src="/image/external?referer=<?php echo $this->originalUrl; ?>&url=<?php echo $this->url; ?>" />
                <?php endif; ?>
            </div>

            <div role="tabpanel" class="tab-pane" id="source">
                <textarea style="width:100%; height:500px;"><?php echo $this->html; ?></textarea>
            </div>

            <div role="tabpanel" class="tab-pane" id="curl">
                <?php _d(parse_url($this->url)); ?>
                <?php _d($this->curl); ?>
            </div>
        </div>
    </div>
</div>