<?php
$curl = new God_Model_Curl;
?>
<div class="row">
    <div class="col-md-12">
        <form action="" method="get" class="form-horizontal">
            <div class="input-group col-md-12">
                <input type="text" name="url" class="form-control input-md" value="<?php echo $this->url ?>">
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-primary btn-md">Go</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class=""row">
    <div class="col-md-12">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#images" aria-controls="images" role="tab" data-toggle="tab">Images</a></li>
            <li role="presentation"><a href="#source" aria-controls="source" role="tab" data-toggle="tab">Source</a></li>
            <li role="presentation"><a href="#curl" aria-controls="curl" role="tab" data-toggle="tab">Curl</a></li>
        </ul>

        <?php _d(count($this->imageElements)); ?>

        <!-- Tab panes -->
        <div class="tab-content">

            <div role="tabpanel" class="tab-pane active" id="images">
                <?php if ($this->imageElements && stristr($this->contentType, 'text/html') !== false): ?>
                <h1>Showing HTML</h1>
                <?php foreach($this->imageElements as $imageElement): ?>
                    <div class="col-xs-4 col-sm-3 col-md-2">
                        <a class="thumbnail" href="<?php echo $this->url(array('controller' => 'browser', 'action' => 'index')) .'?' . http_build_query(array('url' => $curl->normalizeURL($imageElement['href'], $this->url))); ?>">
                            <img src="/image/external?referer=<?php echo $this->url; ?>&url=<?php echo $curl->normalizeURL($imageElement['img'], $this->url); ?>" />
                        </a>
                    </div>
                <?php endforeach; ?>
                <?php endif; ?>

                <?php if ($this->contentType == 'image/jpeg'): ?>
                    <h1>Showing image</h1>
                    <img src="/image/external?referer=<?php echo $this->originalUrl; ?>&url=<?php echo $this->url; ?>" />
                <?php endif; ?>
            </div>

            <div role="tabpanel" class="tab-pane" id="source">
                <textarea style="width:100%; height:300px;"><?php echo $this->html; ?></textarea>
            </div>

            <div role="tabpanel" class="tab-pane" id="curl">
                <?php _d($this->contentType); ?>
            </div>
        </div>
    </div>
</div>