<ul class="nav nav-pills">
    <li<?php echo $this->active == 'view' ? ' class="active"' : '' ?>>
        <a href="<?php echo $this->url(array('controller'=>'model', 'action'=>'view', 'id' => $this->model->ID), null, true);?>">Gallery</a>
    </li>
    <li<?php echo $this->active == 'edit' ? ' class="active"' : '' ?>>
        <a href="<?php echo $this->url(array('controller'=>'model', 'action'=>'edit', 'id' => $this->model->ID), null, true);?>">Edit</a>
    </li>
    <li<?php echo $this->active == 'weburl' ? ' class="active"' : '' ?>>
        <a href="<?php echo $this->url(array('controller'=>'web-url', 'action'=>'index', 'modelid' => $this->model->ID), null, true);?>">Web URL</a>
    </li>
    <li<?php echo $this->active == 'webcrawler' ? ' class="active"' : '' ?>>
        <a href="<?php echo $this->url(array('controller'=>'webcrawler', 'action'=>'index', 'modelid' => $this->model->ID), null, true);?>">Webcrawler</a>
    </li>
</ul>