<?php if ($this->model) : ?>
    <?php
    $this->title = $this->model->getName();
    $this->headTitle($this->model->getName());
    ?>
    <?php $this->model->getName(); ?>

    <?php echo $this->partial('model/partials/navigation.phtml', array('model' => $this->model, 'active' => 'webcrawler')); ?>
<?php endif; ?>

<?php if ($this->domain): ?>
    <?php
    $this->title = $this->domain->domain;
    $this->headTitle($this->domain->domain);
    ?>
<?php endif; ?>

<?php
$this->subtitle = 'Web Urls';
$this->headTitle('Web Urls');
?>

<?php if ($this->webUrls): ?>

    <?php foreach ($this->webUrls as $url): ?>

        <div class="row">
            <div class="col-md-1 col-sm-1 col-xs-2"><a href="<?php echo $this->url(array('controller' => 'webcrawler-url', 'action' => 'test', 'id' => $url['id']), 'default', true); ?>"><?php echo $url['id']; ?></a></div>
            <div class="col-md-6 col-sm-5 col-xs-10"><?php echo $url['url']; ?> <a href="<?php echo $url['url']; ?>" target="_blank"><i class="fa fa-external-link"></i></a></div>
            <div class="col-md-1 col-sm-1 col-xs-2"><?php echo $url['statuscode']; ?></div>

            <div class="col-md-2 col-sm-2 col-xs-5">
                <select>
                    <option>To Do</option>
                </select>
                <span class="hidden-sm hidden-xs"><?php echo 'action'; ?></span>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-5">

                <?php //_dexit($url); ?>

                <?php if ($url['modelnamelinks']): ?>
                    <ul class="list-unstyled">
                        <?php foreach ($url['modelnamelinks'] as $modelNameLink): ?>
                            <li><a href="<?php echo $this->url(array('controller'=>'webcrawler-url', 'action'=>'index', 'modelid' => $modelNameLink['modelName']['model_id']), 'default', true); ?>"><?php echo $modelNameLink['modelName']['name']; ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>

            <?php
            $thumbnails = array();

            if ($url['links'] && $url['domain']['link_depth'] == 1) {
                foreach ($url['links'] as $link) {
                    $thumbnails[] = $link['url'];
                }
            }

            if ($url['links'] && $url['domain']['link_depth'] == 2) {
                foreach ($url['links'] as $link) {
                    foreach ($link['url']['links'] as $links) {
                        if (strpos($links['url']['contenttype'],'image/jpeg') !== false) {
                            $thumbnails[] = $links['url'];
                        }
                    }
                }
            }
            ?>

            <?php if ($thumbnails): ?>
            <div class="col-md-12">
                <?php foreach($thumbnails as $thumbnail): ?>
                    <div class="col-lg-1 col-sm-3 col-xs-3" >
                        <a class="thumbnail small" href="/image/external?referer=<?php echo $url['url']; ?>&url=<?php echo $thumbnail['url']; ?>" target="_blank" title="<?php echo $thumbnail['contentlength']; ?>">
                            <div class="image thumb">
                                <img src="/image/external?referer=<?php echo $url['url']; ?>&url=<?php echo $thumbnail['url']; ?>&width=80" />
                            </div>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>

    <?php echo $this->partial('pagination.phtml', array('paginator' => $this->paginator))?>

<?php else: ?>

    <div class="row">
        <div class="col-md-12">
            <p>No URLS</p>
        </div>
    </div>
<?php endif; ?>


