<?php
    $this->title = '<a href="' . $this->url(array('controller' => 'model', 'action' => 'view', 'id' => $this->photoset->model->ID), null, true) . '">' . $this->photoset->model->getName() . '</a>';
    $this->headTitle($this->photoset->name);
?>

<?php echo $this->photoset->name; ?>

<?php if ($this->files): ?>
<form action="" method="post">
    <ul id="photosets" class="clearfix">
        <?php foreach ($this->files as $file):?>
        <li>
            <img src="<?php echo $this->url(array('controller' => 'image', 'action' => 'thumbnail', 'id' => rawurlencode($file['uri']), 'photoset' => null)); ?>" />
            <input type="radio" id="<?php echo $file['name']; ?>" name="thumbnail" value="<?php echo $file['uri']; ?>" <?php echo $photoset->thumbnail == $file['uri'] ? ' checked="checked"' : ''; ?> />
        </li>
        <?php endforeach; ?>
    </ul>
    <button type="submit">Update</button>
</form>
<?php endif; ?>