<?php
    $this->title = '<a href="' . $this->url(array('controller' => 'model', 'action' => 'view', 'id' => $this->photoset->model->ID), null, true) . '">' . $this->photoset->model->getName() . '</a>';
    $this->headTitle($this->photoset->name);
    $this->headTitle($this->photoset->model->getName());
?>

<?php echo $this->photoset->name; ?>

<form action="<?php echo $this->url(array('action' => 'thumbnail')); ?>" method="post">

    <?php if (is_array($this->files)): ?>
        <ul id="photosets" class="clearfix">
            <?php foreach ($this->files as $file):?>
            <li class="<?php echo $this->photoset->thumbnail != $file['uri'] ? '' : 'autoThumb'; ?>">
                <label for="<?php echo md5($file['name']); ?>" class="image" >
                    <img src="<?php echo $this->url(array('controller' => 'image', 'action' => 'thumbnail', 'id' => rawurlencode($file['uri']), 'photoset' => null)); ?>" />
                </label>
                <input type="radio" id="<?php echo md5($file['name']); ?>" name="thumbnail" value="<?php echo $file['uri']; ?>" <?php echo $this->photoset->thumbnail == $file['uri'] ? ' checked="checked"' : ''; ?> />
            </li>
            <?php endforeach; ?>
        </ul>
    <?php else:?>
        <div>
            <?php echo $this->files; ?>
        </div>
    <?php endif; ?>
    <input type="hidden" name="referer" value="<?php echo array_key_exists('HTTP_REFERER', $_SERVER) ? $_SERVER['HTTP_REFERER'] : ''; ?>" />
    <button type="submit">Update</button>
    <input type="checkbox" name="disable" value="1" id="disableCheckbox" <?php echo $this->photoset->active ? '' : ' checked="checked"'; ?> /><label for="disableCheckbox">Disable photoset</label>
</form>