<?php
    $this->title = '<a href="' . $this->url(array('controller' => 'model', 'action' => 'view', 'id' => $this->model->ID), null, true) . '">' . $this->model->names[0]->name . '</a>';
    $this->headTitle($this->model->names[0]->name);
?>

<?php echo $this->model->photosets[0]->name; ?>

<?php if ($this->files): ?>
    <ul id="photosets" class="clearfix">
        <?php echo $this->partialLoop('GalleryPartial.phtml', $this->files); ?>
    </ul>
<?php endif; ?>